### ISSUE TITLE
Info subpage - Map

### ISSUE THREAD

**Issue by Gripping** [Schandorff/Codegarden#12]
Do documentation
Do Umbraco document types
Do HTML
Do CSS

The map is an interactive (filterable?) map that shows nearby parks, parking, bars, restaurants and hotels. Maybe even mini-concerts around Odense, available pub crawls and other attractions like, sightseeing, boat trips, rent a canoe, etc.

**Comment by npes** [comment]
Map of odense (Bars, transportation, Parking, Restaurants, tourist office, parks, public toilets)
Checkbuttons to turn filters on/off. example: https://wiseoldman.github.io/freePee/src/
