### ISSUE TITLE
Ideas - figure out what we wanna do

### ISSUE THREAD

**Issue by Schandorff** [Schandorff/Codegarden#2]

**Comment by npes** [comment]
We want to see an idea that fulfills the requirements from the description on fronter. 

Use prototypes, wireframes and designs in your presentation.

Content inspiration: https://codegarden17.com/

From project description:
Program
Who is HQ and what do they look like.
Presenting Odense DOK5000 and other communication for the participants of the event 
Map of Odense, bars, restaurants etc.
Polls, awards etc.
More ideas will be appreciated.

**Comment by Schandorff** [comment]
https://docs.google.com/document/d/16Jx4FK1AyZKXvhVvuCpj0fdW9wRkA7IrNtCe_kwuox4/edit
